Modified tests to use users from json files and security tokens.
pbnl/ScoTooBo pull request #69
Opened 2018-04-28 17:58 UTC by NKPmedia

Before they used the normal login form.

2018-05-01 18:49 UTC, bone4 commented on user-test-data/BuvoUser.json
> +}
no new line at end of file

2018-05-01 18:49 UTC, bone4 commented on user-test-data/StavoAmbrone.json
> +}
no new line at end of file

2018-05-01 18:49 UTC, bone4 commented on user-test-data/TestGrueppling.json
> +}
no new line at end of file

2018-05-01 18:49 UTC, bone4 commented on user-test-data/Tronjer.json
> +}
no new line at end of file

2018-05-01 18:50 UTC, bone4 requested changes
sieht bis auf die vier Zeilenende inhaltlich gut aus

2018-09-07 12:03 UTC, NKPmedia commented on user-test-data/Tronjer.json
> +}
Added

2018-09-07 12:03 UTC, NKPmedia commented on user-test-data/TestGrueppling.json
> +}
Added

2018-09-07 12:03 UTC, NKPmedia commented on user-test-data/StavoAmbrone.json
> +}
Added

2018-09-07 12:03 UTC, NKPmedia commented on user-test-data/BuvoUser.json
> +}
Added

2018-09-07 12:07 UTC, merged